twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        default_picture: '%default_picture%'
        arrow_page_up_on: '%arrow_page_up_on%'
        trick_per_page: '%trick_per_page%'
        number_card_by_slide: '%number_card_by_slide%'
        comment_per_page: '%comment_per_page%'
        picture_trick_upload_directory: '%picture_trick_upload_directory%'
        photo_user_upload_directory: '%photo_user_upload_directory%'
        icons_directory: '%icons_directory%'
when@test:
    twig:
        strict_variables: true
